twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic:    /cmd_vel_joy
        timeout:  0.5
        priority: 100
      keyboard:
        topic:    /key_vel
        timeout:  0.5
        priority: 50
      navigation:
        topic:    /cmd_vel_nav    # Nav2 controller_server output
        timeout:  0.5
        priority: 10
 
